CREATE TABLE IF NOT EXISTS public.email_templates (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name character varying(255) NOT NULL,
  category character varying(100) NOT NULL,
  subject character varying(512) NOT NULL,
  body text NOT NULL,
  is_active boolean DEFAULT true NOT NULL,
  created_by_user_id bigint REFERENCES public.users(id) ON DELETE SET NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  deleted_at timestamp with time zone
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_email_templates_name_active
  ON public.email_templates (lower(btrim(name)))
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_email_templates_active
  ON public.email_templates (is_active)
  WHERE deleted_at IS NULL;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'emails_template_id_fkey'
  ) THEN
    ALTER TABLE public.emails
      ADD CONSTRAINT emails_template_id_fkey
      FOREIGN KEY (template_id) REFERENCES public.email_templates(id) ON DELETE SET NULL;
  END IF;
END $$;

INSERT INTO public.email_templates (name, category, subject, body, is_active, created_at, updated_at)
SELECT t.name, t.category, t.subject, t.body, true, now(), now()
FROM (
  VALUES
    (
      'Initial Agent Outreach',
      'Agent Email',
      'New Transaction Opened — {{property_address}}',
      'Hi {{agent_name}},\n\nI''ve opened a new transaction file for {{property_address}}. I''ll be your transaction coordinator for this deal.\n\nPlease send over any documents you have so far, and I''ll begin processing the file.\n\nBest regards,\nKathryn Santos'
    ),
    (
      'Document Request',
      'Document Request',
      'Documents Needed — {{property_address}}',
      'Hi {{agent_name}},\n\nI''m reaching out regarding the transaction at {{property_address}}. The following documents are still needed:\n\n{{document_list}}\n\nPlease send these at your earliest convenience.\n\nThank you,\nKathryn Santos'
    ),
    (
      'Deadline Reminder',
      'Contact Reminder',
      'Upcoming Deadline — {{deadline_name}} — {{property_address}}',
      'Hi {{agent_name}},\n\nThis is a reminder that the {{deadline_name}} for {{property_address}} is due on {{deadline_date}}.\n\nPlease ensure all required items are submitted before this date.\n\nBest regards,\nKathryn Santos'
    ),
    (
      'Escrow Update',
      'Agent Email',
      'Escrow Update — {{property_address}}',
      'Hi {{agent_name}},\n\nHere''s a quick update on the escrow for {{property_address}}:\n\n{{update_details}}\n\nPlease let me know if you have any questions.\n\nBest regards,\nKathryn Santos'
    ),
    (
      'Close of Escrow Confirmation',
      'Agent Email',
      'Congratulations — {{property_address}} Has Closed!',
      'Hi {{agent_name}},\n\nI''m happy to confirm that escrow for {{property_address}} has officially closed and been recorded.\n\nIt''s been a pleasure coordinating this transaction. I look forward to working with you again!\n\nWarm regards,\nKathryn Santos'
    )
) AS t(name, category, subject, body)
WHERE NOT EXISTS (
  SELECT 1
  FROM public.email_templates et
  WHERE lower(btrim(et.name)) = lower(btrim(t.name))
    AND et.deleted_at IS NULL
);

