CREATE TABLE IF NOT EXISTS public.project_task_notes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_task_id bigint NOT NULL REFERENCES public.project_tasks(id) ON DELETE CASCADE,
  author_user_id bigint REFERENCES public.users(id) ON DELETE SET NULL,
  body text NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_project_task_notes_task_id ON public.project_task_notes(project_task_id);
