CREATE TABLE IF NOT EXISTS public.project_timeline_notes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id bigint NOT NULL REFERENCES public.projects(id) ON DELETE CASCADE,
  field_key text NOT NULL,
  author_user_id bigint REFERENCES public.users(id) ON DELETE SET NULL,
  body text NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_project_timeline_notes_project_id ON public.project_timeline_notes(project_id);
CREATE INDEX IF NOT EXISTS idx_project_timeline_notes_field_key ON public.project_timeline_notes(project_id, field_key);
