-- Email compose attachments + hide outbound-only files from transaction file browser

ALTER TYPE public.file_source ADD VALUE 'email_outbound';

CREATE TABLE IF NOT EXISTS public.email_attachments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email_id bigint NOT NULL REFERENCES public.emails(id) ON DELETE CASCADE,
  stored_file_id bigint NOT NULL REFERENCES public.stored_files(id) ON DELETE RESTRICT,
  display_name character varying(512) NOT NULL,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_email_attachments_email_id ON public.email_attachments(email_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_email_attachments_stored_file_id ON public.email_attachments(stored_file_id);
